<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.2" />
    <PackageReference Include="SimpleW" Version="26.1.0-alpha.20260812-2015" />
    <PackageReference Include="SimpleW.Engine.Ioxide" Version="26.1.0-alpha.20260812-2017" />    
  </ItemGroup>

</Project>
