<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="Services/Database.fs" />
    <Compile Include="Services/Dataset.fs" />
    <Compile Include="Services/Items.fs" />
    <Compile Include="Services/Fortunes.fs" />
    <Compile Include="Views.fs" />
    <Compile Include="Handlers.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Oxpecker" Version="2.1.1" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.17" />
  </ItemGroup>

</Project>
